# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-15 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20171214_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='students',
            new_name='student',
        ),
    ]
